########################################################
###   ZUUL 辅助服务
########################################################
spring.application.name: SYNCH-EUREKA-SERVICE
eureka.client.serviceUrl.defaultZone: http://127.0.0.1:8761/eureka/
#eureka.client.serviceUrl.defaultZone: http://127.0.0.1:19002/eureka/
eureka.instance.preferIpAddress: true
eureka.instance.instance-id: ${spring.cloud.client.ipAddress}:${server.port}
server.port: 8060

# ZUUL actuator功能
management.security.enabled: false

logging.file: ../logs/${spring.application.name}.log

########################################################
###  数据库 mysql基本配置；
########################################################
spring.datasource.skytrain:
  url: jdbc:mysql://127.0.0.1:3306/zoner?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
  username: root
  password: root
#  password: ####
  driverClassName: com.mysql.jdbc.Driver

########################################################
###  KAFKA 基本配置
########################################################
spring.kafka.bootstrap-servers: 127.0.0.1:9092
# 生产者和消费者topic前缀
spring.kafka.topicPrefix: sag.

spring.kafka.producer.numOfPartition: 4
spring.kafka.producer.retries: 2
# 每次批量发送消息的数量
spring.kafka.producer.batch-size: 16384
spring.kafka.producer.buffer-memory: 33554432

#网关预警服务邮箱接口
ALARM_EMAIL_ADDRESS: http://127.0.0.1:8070/alarmEmail/sendAlarmEmail

#eureka-server名字
EUREKA_SERVER_NAME: GANTRY-EUREKA-SERVER
